// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBufyqke36PezRQmqYNMftiWw_AcrPOnc',
    appId: '1:819277187281:web:7d9399f8fea378aad7ddf0',
    messagingSenderId: '819277187281',
    projectId: 'flutter-crud-firebase-f1147',
    authDomain: 'flutter-crud-firebase-f1147.firebaseapp.com',
    storageBucket: 'flutter-crud-firebase-f1147.firebasestorage.app',
    measurementId: 'G-V2M92P4X87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPIimnEHVQCEJloxcPaFaFzvuFBPJFFGg',
    appId: '1:819277187281:android:8e6b8dee3815dfa2d7ddf0',
    messagingSenderId: '819277187281',
    projectId: 'flutter-crud-firebase-f1147',
    storageBucket: 'flutter-crud-firebase-f1147.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuYA1sJWFINsdEaqKOTaP2lW3IAUFx0Oc',
    appId: '1:819277187281:ios:e3b5e928ca6a37a9d7ddf0',
    messagingSenderId: '819277187281',
    projectId: 'flutter-crud-firebase-f1147',
    storageBucket: 'flutter-crud-firebase-f1147.firebasestorage.app',
    iosBundleId: 'com.example.modul9FlutterCrudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuYA1sJWFINsdEaqKOTaP2lW3IAUFx0Oc',
    appId: '1:819277187281:ios:e3b5e928ca6a37a9d7ddf0',
    messagingSenderId: '819277187281',
    projectId: 'flutter-crud-firebase-f1147',
    storageBucket: 'flutter-crud-firebase-f1147.firebasestorage.app',
    iosBundleId: 'com.example.modul9FlutterCrudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBufyqke36PezRQmqYNMftiWw_AcrPOnc',
    appId: '1:819277187281:web:0e8ae5bf4ce0dd18d7ddf0',
    messagingSenderId: '819277187281',
    projectId: 'flutter-crud-firebase-f1147',
    authDomain: 'flutter-crud-firebase-f1147.firebaseapp.com',
    storageBucket: 'flutter-crud-firebase-f1147.firebasestorage.app',
    measurementId: 'G-07LW7K31DN',
  );

}